// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Chicken.Gnome.TrayIcon {

	internal class ObjectManager {

		static bool initialized = false;
		// Call this method from the appropriate module init function.
		public static void Initialize ()
		{
			if (initialized)
				return;

			initialized = true;
			GLib.ObjectManager.RegisterType("EggTrayIcon", "Chicken.Gnome.TrayIcon,TrayIcon");
		}
	}
}
